version: '3'
services:

  db:
    container_name: db
    hostname: db
    image: postgres:13-alpine3.16
    env_file:
      - ./.env
    restart: always
    expose:
      - '5432'
    ports:
      - 5432:5432
  
  worker:
    build: ./notifications_service/worker
    container_name: worker
    restart: always
    depends_on:
      - db
      - rabbitmq
      - notifications
    env_file:
      - ./.env
    volumes:
      - ./notifications_service/worker:/worker
    ports:
      - 5678:5678 

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    env_file:
      - ./.env
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:7.0.5
    container_name: redis
    hostname: redis
    restart: always
    expose:
      - "6379"
    ports:
      - 6379:6379

  cinema_together:
    build: ./cinema_together/.
    container_name: cinema
    hostname: cinema
    restart: always
    depends_on:
      - db
      - redis
    volumes:
    - ./cinema_together/app:/opt/app
    env_file:
      - ./.env
    # ports:
    #   - 8000:8000
    # expose:
    #   - 8000

  auth:
    build: ./flask_auth
    container_name: auth
    hostname: auth
    restart: always
    depends_on:
      - db
      - redis
    command: >
      bash -c "python ping.py && alembic upgrade head && flask utils_bp init_db && python3 -m debugpy --listen 0.0.0.0:5681 pywsgi.py"
    volumes:
      - ./flask_auth/src:/opt/app/src
    env_file:
      - ./.env
    ports:
      - 8001:8001
      - 5681:5681
    # expose:
    #   - 8001

  notifications:
    build: ./notifications_service/api_notifications
    container_name: notifications
    hostname: notifications
    restart: always
    depends_on:
      - rabbitmq
      - db
    volumes:
      - ./notifications_service/api_notifications:/opt/app
    env_file:
      - ./.env
    ports:
      - 8002:8002
    # expose:
    #   - 8002

  # nginx:
  #   build: ./nginx
  #   container_name: nginx
  #   restart: always
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
  #     - ./nginx/data:/data/
  #   depends_on:
  #     - cinema_together
  #     # - notifications
  #     - auth
  #   ports:
  #     - "8000:8000"
  #     - "8001:8001"
  #     # - "8002:8002"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTVmY2Y3MTYtNDEyMS00YjY0LWIyM2ItYjZkNjNhMTRhODUwIiwicm9sZXMiOiJmOGY1ZWU1OS1hZjg2LTRmZDMtYTExZi03NWQyMzNkYmQ3ZmEiLCJpYXQiOjE2ODk3MDkwNjMuMzEwMzU1LCJleHAiOjI2OTEwMDUwNjMuMzEwMzU1LCJ0b2tlbl90eXBlIjoiYWNjZXNzIn0.XkSHaBY7MTKUbFI9BtODf5LO_igE90syeNAh_WDrc5Y